create database if not exists EcoFood;
use EcoFood;



CREATE TABLE IF NOT EXISTS Tipo_Empresa (
    ID_Tipo_Empresa INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    Descricao VARCHAR(1) NOT NULL,
	FK_ID_Empresa VARCHAR(18) NOT NULL,
	FOREIGN KEY (FK_ID_Empresa) REFERENCES Empresa(CNPJ)
);

CREATE TABLE IF NOT EXISTS Endereco (
    ID_Endereco INT PRIMARY KEY AUTO_INCREMENT,
    Numero VARCHAR(10) NOT NULL,
    Complemento VARCHAR(100),
    Logradouro VARCHAR(200) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    Bairro VARCHAR(100) NOT NULL,
    Municipio VARCHAR(100) NOT NULL,
    Estado CHAR(20) NOT NULL,
	FK_ID_Empresa VARCHAR(18) NOT NULL,
	FOREIGN KEY (FK_ID_Empresa) REFERENCES Empresa(CNPJ)
);

CREATE TABLE IF NOT EXISTS Empresa (
	CNPJ VARCHAR(18) PRIMARY KEY NOT NULL,
    Nome_Fantasia VARCHAR(100) NOT NULL,
    Razao_Social VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Produto (
    ID_Produto INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Categoria VARCHAR(100) NOT NULL,
    Quantidade DECIMAL(10,2) NOT NULL,
    Validade DATE NOT NULL,
    Data_Registro DATE NOT NULL,
	FK_ID_Empresa VARCHAR(18) NOT NULL,
	FOREIGN KEY (FK_ID_Empresa) REFERENCES Empresa(CNPJ)
);

CREATE TABLE IF NOT EXISTS Lote (
    ID_Lote INT PRIMARY KEY NOT NULL,
    FK_ID_Produto INT NOT NULL,
    FK_ID_Doacao INT NOT NULL,
    FOREIGN KEY (FK_ID_Produto) REFERENCES Produto (ID_Produto),
    FOREIGN KEY (FK_ID_Doacao) REFERENCES Doacao (ID_Doacao)
);

CREATE TABLE IF NOT EXISTS Doacao (
    ID_Doacao INT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_Tipo_Empresa INT,
    Descricao VARCHAR(255) NOT NULL,
    FOREIGN KEY (FK_ID_Tipo_Empresa) REFERENCES Tipo_Empresa(ID_Tipo_Empresa)
);

CREATE TABLE IF NOT EXISTS Login (
    CNPJ VARCHAR(18) NOT NULL,
    Senha VARCHAR(255) NOT NULL,
    FOREIGN KEY (CNPJ) REFERENCES Empresa(CNPJ)
);

CREATE TABLE IF NOT EXISTS Contato (
	ID_Contato INT PRIMARY KEY AUTO_INCREMENT,
    DDD CHAR(3) NOT NULL,
    Telefone VARCHAR(18) NOT NULL,
    Celular VARCHAR(18),
    Email VARCHAR(150),
    FK_CNPJ VARCHAR(18),
    FOREIGN KEY (FK_CNPJ) REFERENCES Empresa(CNPJ)
);